name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      -  'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          pr-mode: True
          args: --apply-fixes
          push-fixes: pull-request
    
      - name: 'LS Results'
        run: ls -lahR ${{ runner.temp }}
        
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: 'SARIF Results'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json

 
